- deploy/crds/v1/policy.open-cluster-management.io_configurationpolicies.yaml
- pkg/apis/policy/v1/configurationpolicy_types.go
The config policy does not work properly without preserving some existing fields.  This behaves differently than the upgrade scenario for v1beta1 to v1 so I didn't catch it initially.
This fix will be needed for issue https://github.com/open-cluster-management/backlog/issues/9739 too
> need this preserve flag in the v1 crds

- pkg/controller/configurationpolicy/configurationpolicy_utils.go
- test/e2e/case7_no_spec_test.go
> do not patch existing lists with the sorted version

- CONTRIBUTING.md
- README.md
To help new users/contributors get up to speed on this component, I think an example YAML and some description of what each field does would be very helpful.  Additionally, the requirements around contributing are more clear in the community's template, so I've pulled that information into this repo.
@ycao56, I hadn't noticed your PR https://github.com/open-cluster-management/config-policy-controller/pull/111 when I made this, there is definitely overlap in our changes, sorry.
Regarding some of the fields in the table, I noticed (and tested) that the specific options for `remediationAction` and `complianceType` are not enforced by the controller. Arbitrary values can be input into those fields and the spec is not rejected: it just leads to (possibly) unexpected behavior. Similarly, most …
> Doc Update

- pkg/controller/configurationpolicy/configurationpolicy_controller.go
- pkg/controller/configurationpolicy/configurationpolicy_controller_test.go
When using an `inform` policy that `musthave` a certain resource, the compliance should be based off the evaluation results coming from each namespace where the policy is applied/selected.  Instead of one compliant namespace making the policy Compliant, each selected namespace must be compliant to make the policy compliant.
> change the way compliance is handled across multiple namespaces

- pkg/controller/configurationpolicy/configurationpolicy_controller.go
- pkg/controller/configurationpolicy/configurationpolicy_utils.go
During the 2.3 retrospective, we talked about the health of the GRC codebase not being as good as it could be. As the configuration policy controller is one of the more confusing and less documented repos GRC manages, this PR:
- adds comments
- renames some variables for clarity
- removes some dead code
> clean up code

- pkg/controller/configurationpolicy/configurationpolicy_controller.go
fixes comments in the merge function to reflect its new behavior after https://github.com/open-cluster-management/config-policy-controller/commit/8f5d4c19e4c65cdaf6a31e4a1f142f841e7f4631
> edit comment in merge specs to reflect new behavior

- pkg/controller/configurationpolicy/configurationpolicy_controller.go
- test/e2e/case12_list_compare_test.go
- test/e2e/e2e_suite_test.go
- test/resources/case12_list_compare/case12_whitespace_create.yaml
When merging lists, it was trimming whitespace from some of the items. In cases where a resource has a string in a list, this caused the controller to append a duplicate of the item every time it enforced the configuration. This issue recently appeared in framework tests from a gatekeeper resource (with a string ending in a newline) that was being created.
Previously, the issue would not appear as often, because if the cluster resource's list had 1 item, and the policy template's list had 1 item, the template would overwrite the cluster configuration. That behavior was recently changed so that if the "new" item and "old" item don't match, the new item is appended to the list. (Note - previous behavior of overwriting the list can still be accomplished through `mustonlyhave` policies).
> Whitespace in lists

- go.mod
- go.sum
- pkg/controller/configurationpolicy/configurationpolicy_controller.go
This updates the dependency on the go-template-utils module.
This depends on https://github.com/open-cluster-management/go-template-utils/pull/7
Resolves https://github.com/open-cluster-management/backlog/issues/14952
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Use the latest templates API

- pkg/controller/configurationpolicy/configurationpolicy_controller.go
- pkg/controller/configurationpolicy/configurationpolicy_controller_test.go
This fixes the situation where the controller is comparing what is in
the policy versus what already exists, and the object being compared
contains an integer.
The code in the mergeSpecs function marshals and unmarshals the existing
object and the object in the policy. Presumably this is to create a copy
of the objects before modification. By doing so with the encoding/json
package, it converts any integers to float64.
This caused an issue in the checkFieldsWithSort function which compared
the existing object with the merged object, since the existing object
referenced here did not go through the marshal and unmarshal process,
but the merged object did. This meant that the integers in the merged
object were of type float64, but they remained integers in the existing
object. When …
> Fix an issue that caused integer comparison to fail

- go.mod
- go.sum
This makes the code consistent with the policy propagator in:
https://github.com/open-cluster-management/governance-policy-propagator/pull/101
> Update go-template-utils to v1.2.1

- go.mod
- go.sum
This is to include the fix from:
https://github.com/open-cluster-management/go-template-utils/pull/18
> Update go-template-utils to v1.2.2

- go.mod
- go.sum
This fixes a regression as described in:
https://github.com/open-cluster-management/go-template-utils/pull/19
> Update go-template-utils to v1.2.3

- pkg/controller/configurationpolicy/configurationpolicy_controller.go
- test/e2e/case13_templatization_test.go
- test/resources/case13_templatization/case13_update_referenced_object.yaml
Deep copy the policy before passing it to handleObjectTemplates since even
though handleObjectTemplates accepts a copy (i.e. not a pointer) of the
policy, policy.Spec.ObjectTemplates is a slice of pointers, so any
modifications to the objects in that slice will be reflected in
the PolicyMap cache, which can have unintended side effects.
This manifested itself when a policy has templates which when resolved,
still have intentional template delimiters (i.e. {{ and }}) in the result.
On the first time being processed, everything would go well. On the
second or third time, when the policy cache was not updated again by the
reconciler, the policy in the cache already had resolved templates. This
would lead to the templates code trying to reprocess the already
resolved policy.
Additionally to …
> Protect the policy cache from unintended updates

- pkg/controller/configurationpolicy/configurationpolicy_controller.go
https://github.com/open-cluster-management/backlog/issues/16674
Setting this annotation on the configuration policy template will prevent any template processing.
"policy.open-cluster-management.io/disable-templates" :  "true"
> Annotation to disable templates

- controllers/configurationpolicy_utils.go
- test/e2e/case12_list_compare_test.go
- test/resources/case12_list_compare/case12_byte_create.yaml
- test/resources/case12_list_compare/case12_byte_inform.yaml
Fixes a rare issue where if an object contained a quantity of bytes (ex: a `memory` field) that was too large, it would appear as a rounded string in the existing object and not in the template (ex: `1Gi` in the existing object and `1024Mi` in the template). This would incorrectly be flagged as a mismatch, causing issues like https://github.com/open-cluster-management/backlog/issues/17508 .
> add special equality check for quantities of bytes

- pkg/controller/configurationpolicy/configurationpolicy_controller.go
Backporting fix for #16674 to release-2.3 to allow disabling a template processing through an annotation.
Unable to cherry-pick due to various changes in 2.4 that are not in 2.3.
issue# https://github.com/open-cluster-management/backlog/issues/16674
> Support Annotation to disable go-template processing

- test/resources/case15_event_format/case15_parent_alwayscompliant.yaml
- test/resources/case15_event_format/case15_parent_becomescompliant.yaml
- test/resources/case15_event_format/case15_parent_becomesnoncompliant.yaml
- test/resources/case15_event_format/case15_parent_nevercompliant.yaml
Previously, the Policy CRD we were using here did not have a spec field,
so these test resources did not need them. But now, since these Policies
are invalid, they are causing problems in the tests.
This makes the Policies for these tests fully valid.
> Add full Policy Spec to event format tests

- controllers/configurationpolicy_controller.go
- controllers/configurationpolicy_controller_test.go
- main.go
- pkg/common/kubeClient.go
- pkg/common/namespace_selection.go
- pkg/common/namespace_selection_test.go
While preparing for some logging adjustments, I noticed some bits that I felt could be cleaned up.
Main changes:
- The global Recorder is no longer used - the reconciler's recorder is now used in all instances where events should be recorded
- More functions are methods on the Reconciler, so they can use the reconciler's recorder
- The global KubeClient (type `*kubernetes.Interface`) is removed in favor of using the global clientSet, a concrete type which implements that interface.
> Refactor cleanup

- .github/workflows/kind.yml
- build/Dockerfile
- go.mod
Switching to go 1.17 to match what the build is using downstream.
> Move to go 1.17 to match downstream go version

- controllers/encryption.go
- controllers/encryption_test.go
If the Secret has an empty value as the previous key, it shouldn't be cached
since go-template-utils will see it as an empty byte slice instead of a
nil byte slice and error.
> Stop caching empty encryption keys

- api/v1/configurationpolicy_types.go
- controllers/configurationpolicy_controller.go
- controllers/configurationpolicy_controller_test.go
- controllers/configurationpolicy_utils_test.go
- deploy/crds/policy.open-cluster-management.io_configurationpolicies.yaml
- test/e2e/case17_evaluation_interval_test.go
- test/resources/case17_evaluation_interval/policy-never-reevaluate.yaml
- test/resources/case17_evaluation_interval/policy.yaml
- test/utils/utils.go
This adds the field `spec.evaluationInterval` which is a map that
accepts the keys `compliant` and `noncompliant`. Each value is a
duration for the minimum wait time between policy evaluations. The
values can also be set to `never` to disable evaluating the policy
entirely after a certain compliance state is reached. In this case, the
compliance message mentions that it will not be reevaluated.
On the technical implementation side, two new status fields are added.
The first is `status.lastEvaluated` which is a RFC3339/ISO-8601
formatted timestamp. This keeps track of when the policy was last
evaluated for the controller to know when the next evaluation should
take place. It is also useful information for the user.
The second status field that is added is
`status.lastEvaluatedGeneration`, …
> Add a configurable evaluation interval for configuration policies

- controllers/configurationpolicy_controller.go
- test/e2e/case17_evaluation_interval_test.go
- test/resources/case17_evaluation_interval/parent-policy.yaml
- test/resources/case17_evaluation_interval/policy.yaml
An oversight in #235 made it so that a parent policy status update event
was sent every time the policy was evaluated. This reverts some of the
status update tracking removal in that PR.
Refers:
https://github.com/stolostron/backlog/issues/20323
> Send a parent status update event only when the status changed

- main.go
The event recorder has rate limiting in order to prevent multiple
"duplicate" events from being sent in a short time. By default, the
"key" that it uses to determine if an event is a duplicate excludes the
reason and message of the event. This commit adds the reason and message
so that a policy with many configuration policies with frequent status
changes will still produce an event.
Additionally, event aggregation is essentially disabled by resetting the event counter
every second so that events that are common except for the message are not aggregated
to a single event.
> Configure the event recorder to not unnecessarily drop or alter events

- .dockerignore
- controllers/configurationpolicy_controller.go
- go.mod
- go.sum
- test/e2e/case10_kind_field_test.go
- test/e2e/case11_apiserver_config_test.go
- test/e2e/case12_list_compare_test.go
- test/e2e/case13_templatization_test.go
- test/e2e/case15_event_format_test.go
- test/e2e/case18_discovery_refresh_test.go
- test/e2e/case1_pod_handling_test.go
- test/e2e/case2_role_handling_test.go
- test/e2e/case3_imgvuln_test.go
- test/e2e/case4_clusterversion_test.go
- test/e2e/case5_multi_test.go
- test/e2e/case6_no_ns_test.go
- test/e2e/case7_no_spec_test.go
- test/e2e/case8_status_check_test.go
- test/e2e/case9_md_check_test.go
- test/e2e/e2e_suite_test.go
- test/resources/case18_discovery_refresh/policy-template.yaml
- test/resources/case18_discovery_refresh/policy.yaml
- test/resources/case18_discovery_refresh/prereqs-for-template-policy.yaml
Prior to this PR, the API discovery information was refreshed on
every cycle (i.e. every 10 seconds) but this puts unnecessary load on
the Kubernetes API.
This PR makes it so that the API discovery information is refreshed
whenever an API resource (not an object) that is not in the discovery
information is encountered. It is also periodically updated every 10
minutes.
The first commit cleans up the created configuration policies after each test
since the tests that require API Discovery refreshes are slower after this change
and it was interfering with other tests.
Resolves:
https://github.com/stolostron/backlog/issues/20382
> Cache the API discovery information

- Makefile
- go.mod
- main.go
Previously, libraries using `glog` could be configured through a flag
like `-v=3` (or `--v=3`), and this controller's zap logs could be
configured through a flag like `--zap-log-level=3`. However, libraries
using `klog` could not have their logging levels configured, and the
different logs might print differently if zap had JSON mode turned on.
This makes everything more consistent. The `v` flag is now passed on
to `klog`, which is more popular in our dependencies, and that same
flag will override the zap log level. Additionally, klog is sent
through the zap logr, so the formats will be the same.
Refs:
- https://github.com/stolostron/backlog/issues/19030
> Synchronize logging levels with libraries

- controllers/configurationpolicy_utils.go
If a policy specifies an empty array or map in its object definition
and the property is set to `omitEmpty`, then the controller will
mark the policy as noncompliant when it compares the policy with the
object retrieved from the API since the property wouldn't be returned.
This commit makes it so that an omitted array or map value is equal to
it being empty.
> Handle objects that have omitted empty values

- controllers/configurationpolicy_controller.go
- deploy/manager/manager.yaml
- deploy/operator.yaml
- go.mod
- go.sum
- main.go
This improves the format of the logs themselves, and allows for the klog
verbosity to be independently configured. Timestamps are now in ISO-8601
and all logs get nice caller information (file and line number).
This removes the use of controller-runtime's zap wrapper, in favor of
using zapr and zap more directly, for more configuration. The necessary
flags from controller-runtime's wrapper were re-implemented here.
> Configure zap and klog levels separately

- main.go
This hub kubeconfig is used when the `lease` API is not available on the
managed cluster, for example if it is an OCP 3.11 cluster. The name of
the secret with that kubeconfig was not updated when the addon name
changed.
Fixes https://github.com/stolostron/backlog/issues/21200
> Fix default hub kubeconfig name

- controllers/configurationpolicy_controller.go
- test/e2e/case8_status_check_test.go
- test/resources/case8_status_check/case8_pod_change.yaml
- test/resources/case8_status_check/case8_pod_fail.yaml
The upgrade policy had a value in the status and spec sections of a
ClusterVersion resource.  The config policy controller ignored the
update because there was a status update.  Change is to still ignore
the status update, but don't ignore the spec update.
Refs:
- https://github.com/stolostron/backlog/issues/21908
> Status in a policy shouldn't prevent spec updates

- deploy/manager/manager.yaml
- deploy/operator.yaml
- main.go
Previously, the hub kubeconfig was read from a secret. This meant that
if the config expired and the secret was updated, the controller here
would not get the updated cert. Now, we use a volume mount with the
config, which gets automagically updated.
Refs:
- https://github.com/stolostron/backlog/issues/22651
> Use a volume mounted secret for the hub kubeconfig

- .github/workflows/sonarcloud.yml
When SonarCloud was executed, it posted analysis on the commit in the target branch instead of the PR commit.
> Supply the commit hash to SonarCloud

- controllers/configurationpolicy_controller.go
- controllers/configurationpolicy_controller_test.go
- test/e2e/case1_pod_handling_test.go
- test/utils/utils.go
This is a backport of #392 but needed to do it manually due to a test case being slightly different in 2.6.
The status.compliancyDetails[].conditions array was always limited to just a single condition due to a bug. This sets the limit to 10 instead.
Relates:
https://issues.redhat.com/browse/ACM-2708
> [release-2.6] Fix the conditions history in compliancyDetails

- .github/workflows/kind.yml
- Makefile
- build/Dockerfile
- controllers/configurationpolicy_controller.go
- controllers/configurationpolicy_utils.go
- deploy/manager/manager.yaml
- deploy/operator.yaml
- main.go
- main_test.go
- pkg/common/common.go
- pkg/triggeruninstall/triggeruninstall.go
- test/e2e/case29_trigger_uninstall_test.go
- test/resources/case29_trigger_uninstall/policy.yaml
- test/resources/case29_trigger_uninstall/policy2.yaml
This syncs https://github.com/open-cluster-management-io/config-policy-controller/pull/104.
Closes #419.
> Manual sync of #104

- Dockerfile
RHTAP (Red Hat Trusted Application Pipeline) is a new CI/CD tool that we would like to use to build this repo, but it requires (for now) that the Dockerfile exist at the root of the repo!  The RHTAP team suggested we solve this repository's folder-nested Dockerfile with a symbolic link!
> Add a symlink to the Dockerfile at root to allow us to enable RHTAP builds

- controllers/configurationpolicy_controller_test.go
- controllers/configurationpolicy_utils.go
- controllers/configurationpolicy_utils_test.go
- test/e2e/case12_list_compare_test.go
- test/e2e/case20_delete_objects_test.go
- test/e2e/case25_related_object_metric_test.go
- test/e2e/case26_user_error_metric_test.go
- test/e2e/case31_policy_history_test.go
- test/e2e/case8_status_check_test.go
- test/resources/case31_policy_history/pod-config-policy-number.yaml
- test/resources/case31_policy_history/pod-config-policy.yaml
- test/resources/case31_policy_history/pod-policy-number.yaml
- test/resources/case31_policy_history/pod-policy.yaml
Description of problem:
When Pod security policy is created and the status is changed from inform to enforce, the status is toggling. Not able to enforce pod security policy.
(cherry picked from commit b70748b1ac975b4573678740c1b2c8bef4eef4d2)
How to fix
Set default value when Kube API value omitted
ref: https://issues.redhat.com/browse/ACM-3109
Signed-off-by: Yi Rae Kim <yikim@redhat.com>
> Fix status history toggling (#111)

- controllers/configurationpolicy_controller.go
- controllers/configurationpolicy_controller_test.go
- controllers/configurationpolicy_utils.go
- test/e2e/case20_delete_objects_test.go
- test/e2e/e2e_suite_test.go
- test/resources/case20_delete_objects/case20_change_config_policy.yaml
Description of problem:
The pruneObjectBehavior of a ConfigurationPolicy does not help clean up objects when the policy is edited such that the managed object's name is changed. Ideally, editing the policy would result in deleting the old object, if the pruneObjectBehavior field was set.
Signed-off-by: Yi Rae Kim <yikim@redhat.com>
(cherry picked from commit d3603379037f6e48a11077753e5d5331213cdbeb)
> Fix  ConfigurationPolicies are left behind bug

- .github/workflows/kind.yml
- .tekton/config-policy-controller-0pyc-pull-request.yaml
- Makefile
- controllers/configurationpolicy_controller.go
- test/e2e/case20_delete_objects_test.go
Manual sync of:
- https://github.com/open-cluster-management-io/config-policy-controller/pull/117
Closes #466
> Manual sync (#117)

- controllers/configurationpolicy_controller.go
- controllers/configurationpolicy_controller_test.go
- test/e2e/case31_policy_history_test.go
- test/resources/case31_policy_history/long-message-config-policy.yaml
- test/resources/case31_policy_history/long-message-policy.yaml
Description of problem:
The status message for non compliant policy is truncated with "..." when the policy has multiple objectTemplates or a namespace. This leaves the user unable to determine why the policy is non compliant.
Expect result: message should include all information
Signed-off-by: Yi Rae Kim <yikim@redhat.com>
> Bug: Policy compliance status is truncated

- controllers/configurationpolicy_controller.go
Description of problem:
Some HyperShift hosted clusters have been getting stuck in the uninstalling state (without transitioning to the error state), indicating a problem with ACM's deletion of the ManagedCluster object. For these clusters, we've noticed that the ManagedCluster object on the service/hub cluster has a DeletionTimestamp in the past and a status condition of ManagedClusterLeaseUpdateStopped. On the corresponding management cluster, we've noticed that the klusterlet-$CID namespace contains a pod named config-policy-controller-uninstall that's crash-looping with the following error.
Signed-off-by: Yi Rae Kim <yikim@redhat.com>
(cherry picked from commit 7c79594924c40adf6f63091038addf7a125bf65e)
Ref: https://issues.redhat.com/browse/ACM-4854
> [release-2.7] Bug:  crash-looping config-policy-controller-uninstaller

- controllers/configurationpolicy_utils.go
- test/e2e/case15_event_format_test.go
- test/e2e/case17_evaluation_interval_test.go
- test/e2e/case21_alternative_kubeconfig_test.go
- test/e2e/case31_policy_history_test.go
- test/resources/case31_policy_history/event-config-policy-emptystruct.yaml
- test/resources/case31_policy_history/event-policy-emptystruct.yaml
- test/resources/case31_policy_history/rb-config-policy-emptyarray.yaml
- test/resources/case31_policy_history/rb-policy-emptyarray.yaml
Resource does not get created with an empty field and the policy check flip-flops alternatively marking the policy as being compliant and non-compliant
Cherrypick and backport
Ref: https://issues.redhat.com/browse/ACM-3424
> [release-2.7] Policy status toggling continuously after enforcing it.

- controllers/configurationpolicy_controller.go
- test/e2e/case20_delete_objects_test.go
Manual cherry-pick:
- https://github.com/stolostron/config-policy-controller/pull/467
- https://github.com/stolostron/config-policy-controller/pull/470
The refetch was the goal, but it had a partial dependency on the error handling which wasn't a large PR so I've included both commits in their entirety.
ref: https://issues.redhat.com/browse/ACM-4885
> [release-2.7] Manual cherry-pick of status retries

- controllers/configurationpolicy_controller.go
- test/e2e/case30_multiline_templatization_test.go
- test/resources/case30_multiline_templatization/case30_configmaps.yaml
- test/resources/case30_multiline_templatization/case30_policy.yaml
- test/resources/case30_multiline_templatization/case30_unterminated.yaml
This is cherry-picked to address https://issues.redhat.com/browse/ACM-6042.
- Clear compliancyDetails on policy-wide errors
- Reduce the length of the array if the number of object-templates is lower
ref: https://issues.redhat.com/browse/ACM-5512
(cherry picked from commit 9b8a98f2a3fd3088576885f825a5e4a5251f6597)
> [2.7 cherry-pick] Adjust CompliancyDetails array properly

- controllers/configurationpolicy_controller.go
- controllers/configurationpolicy_utils.go
- test/e2e/case15_event_format_test.go
- test/e2e/case17_evaluation_interval_test.go
- test/e2e/case20_delete_objects_test.go
- test/e2e/case21_alternative_kubeconfig_test.go
- test/e2e/case31_policy_history_test.go
- test/resources/case31_policy_history/event-config-policy-emptystruct.yaml
- test/resources/case31_policy_history/event-policy-emptystruct.yaml
- test/resources/case31_policy_history/rb-config-policy-emptyarray.yaml
- test/resources/case31_policy_history/rb-policy-emptyarray.yaml
This reverts commit 45040d55b14b0f19461c280348dceb134a4a8328, bringing back:
- "Add refetch before updating status" 084e54d
- "Tweak error handling" f8d5d9c
- "Fix constantly updating objects with a null struct" d704d5f
- "Fix constantly updating objects with an empty list" 3b1204c
- "Use common parent policy creation function" 38fc8ac
- "Add test for possibly omitted array" fb12e14
> Revert "Revert commits not wanted in 2.7.5"

- Makefile
- README.md
The `ClusterRoleBinding` had a hardcoded namespace, preventing the controller from running in a custom namespace.
(cherry picked from commit bc358da92d003d2a35e5f6b01ff8a195d2f0813a)
Cherry-pick of:
- open-cluster-management-io/config-policy-controller#173
Closes #625
> Manual cherry-pick: Enable configuring the controller namespace

- controllers/configurationpolicy_controller_test.go
- controllers/configurationpolicy_utils.go
A cherry-pick of #608, with conflicts resolved.
> [release-2.8] CHERRYPICK: Fix items in nested lists not always being matched

- controllers/configurationpolicy_controller.go
Solution: when decoding, operate on a copy of the existing object's data
Ref: https://issues.redhat.com/browse/ACM-8739
Signed-off-by: Jeffrey Luo <jeluo@redhat.com>
(cherry picked from commit 2d10d5372515abbcf8bdd89d371325cf686c98e4)
> [Cherry-pick-2.9] Fix bug where decoding stringdata modified the existing object directly

- controllers/configurationpolicy_controller.go
Solution: when decoding, operate on a copy of the existing object's data
Ref: https://issues.redhat.com/browse/ACM-8739
Signed-off-by: Jeffrey Luo <jeluo@redhat.com>
(cherry picked from commit 2d10d5372515abbcf8bdd89d371325cf686c98e4)
> [Cherry-pick-2.8] Fix bug where decoding stringdata modified the existing object directly

- Makefile
Manual cherry-pick of:
- https://github.com/open-cluster-management-io/config-policy-controller/pull/190
(cherry picked from commit 77048df3ca61b976d61f75ec9b1b93b48400c168)
Closes #692 
(My suspicion is the cloning issue will continue until the backup branches are deleted, but I'd like to let the changes marinate before those branches are deleted.)
> Manual cherry-pick: Use `OLM_VERSION`

- .github/workflows/kind.yml
Manual cherry-pick:
- https://github.com/open-cluster-management-io/config-policy-controller/pull/203
Closes #719 
- Removes unnecessary subdirectories in favor of defaults
- Also attempts to resolve the `setup-go` caching warnings.
(cherry picked from commit e08ed0bf7c1754b238cbd0eaca9d3ca30ed70b55)
> [Manual sync] Simplify GitHub Action workflows

- controllers/configurationpolicy_controller.go
- test/e2e/case12_list_compare_test.go
- test/e2e/case2_role_handling_test.go
- test/e2e/e2e_suite_test.go
- test/resources/case2_role_handling/case2_rolebinding_create_enforce.yaml
- test/resources/case2_role_handling/case2_rolebinding_create_patch.yaml
- test/utils/utils.go
The function the code was put in was refactored, but I think I found where it was refactored from...
Manual cherry-pick of commit from:
- #797
> [release-2.9] Cherry-pick: Fix handling of undefined fields for `mustonlyhave`

- test/e2e/case38_install_operator_test.go
This seemed like a worthwhile fix to bring to 2.10 from https://github.com/open-cluster-management-io/config-policy-controller/pull/235 (Note: the main *feature* from that PR is not coming to this release branch, just one test improvement).
> [release-2.10] Wait for actual ConstraintsNotSatisfiable reason

- .github/workflows/kind.yml
- Makefile
The hosted mode tests and the "regular" tests were running in series, and each took about 20 minutes. Now they run in parallel in separate jobs, with a new job to merge their coverage data. Some other "quick" checks (like formatting, linting) were also moved to a separate job, which allows the tests to run even if there is a linting issue.
Refs:
- https://issues.redhat.com/browse/ACM-13032
(cherry picked from commit 8b0aecf8f3dfd6a340a1462ca2ec4432dc4fac1b)
Closes https://github.com/stolostron/config-policy-controller/issues/987
> Split kind.yaml workflow into parallel jobs

- .tekton/config-policy-controller-acm-210-pull-request.yaml
- .tekton/config-policy-controller-acm-210-push.yaml
This update configures the SAST task to upload SARIF results to quay.io for
long-term storage
Related: 
- https://issues.redhat.com/browse/KONFLUX-3663
- https://issues.redhat.com/browse/KONFLUX-2263
> fix(KONFLUX-3663): format PipelineRun files and upload SAST results

- test/crds/securitycontextconstraints.security.openshift.io_crd.yaml
- test/e2e/case7_no_spec_test.go
Manual cherry-pick of:
- #997 
(cherry picked from commit a14266b6f6fca68b598fec6d06641a451a48503a)
> [release-2.8] Use `--server-side` for `null` test

- controllers/operatorpolicy_controller.go
- test/e2e/case38_install_operator_test.go
- test/e2e/e2e_suite_test.go
Previously, if the pacakagemanifest was missing, perhaps due to the operator no longer being available in the catalog, the operator policy would be marked as invalid, and not report on the potentially helpful status of the subscription. Now the existing subscription can be used for the default values, and a more helpful status can be reported.
Refs:
- https://issues.redhat.com/browse/ACM-14617
(cherry picked from commit 56dc174a3d446f48912d12f0b9a70a2402f33449)
> [release-2.12] Adopt existing sub when packagemanifest not found

- build/Dockerfile.rhtap
This pull request adds the repository URL as the 'url' label to container images.
**Related Issue:** https://issues.redhat.com/browse/ACM-23275
**Epic Goal:** All ACM and MCE container images should define the url label pointing to their source repository instead of the generic 'https://www.redhat.com' value.
**Target Branch:** main
**Components affected:** config-policy-controller
**Branch details:** config-policy-controller (revision: main, fast-forwarded to: main)
**Label added:**
- url: https://github.com/stolostron/config-policy-controller
This change improves traceability and helps identify the source repository for each container image, which is especially important for components like kube-rbac-proxy that exist in multiple organizations.
> Add repository url label to container images
