SECURITY.md
Addresses https://github.com/open-cluster-management/backlog/issues/9544
=> Security compliance 9544

pkg/controller/configurationpolicy/configurationpolicy_controller.go, pkg/controller/configurationpolicy/configurationpolicy_utils.go, test/e2e/case12_list_compare_test.go, test/resources/case12_list_compare/case12_pod_create.yaml, test/resources/case12_list_compare/case12_pod_inform.yaml
for https://github.com/open-cluster-management/backlog/issues/10421
=> Enhance list compare

pkg/controller/configurationpolicy/configurationpolicy_controller.go, pkg/controller/configurationpolicy/configurationpolicy_utils.go, test/e2e/case12_list_compare_test.go, test/resources/case12_list_compare/case12_role_create.yaml, test/resources/case12_list_compare/case12_role_inform.yaml
=> enhance generic list check to use sort

go.mod, pkg/common/templates/clusterconfig_funcs.go, pkg/common/templates/generic_lookup_func.go, pkg/common/templates/k8sresource_funcs.go, pkg/common/templates/templates.go, pkg/controller/configurationpolicy/configurationpolicy_controller.go
=> templatized policies

pkg/common/templates/k8sresource_funcs_test.go, pkg/common/templates/templates.go, pkg/common/templates/templates_test.go
=> templates gotest-1

pkg/common/templates/clusterconfig_funcs.go, pkg/common/templates/templates.go, pkg/common/templates/templates_test.go
=> indent func to support certs

CODE_OF_CONDUCT.md, CONTRIBUTING.md, Makefile, OWNERS, README.md, SECURITY.md
=> community template updates

go.mod, go.sum, pkg/common/templates/templates.go, pkg/common/templates/templates_test.go
=> template func for  string to int

Makefile, pkg/common/templates/templates.go, pkg/common/templates/templates_test.go
=> process for datatypes

build/run-e2e-tests.sh, deploy/crds/policy.open-cluster-management.io_configurationpolicies_crd.yaml, go.sum, pkg/apis/policy/v1/configurationpolicy_types.go, pkg/controller/configurationpolicy/configurationpolicy_controller.go, pkg/controller/configurationpolicy/configurationpolicy_controller_test.go, pkg/controller/configurationpolicy/configurationpolicy_utils.go
manual cherry pick of https://github.com/open-cluster-management/config-policy-controller/pull/106
https://github.com/open-cluster-management/backlog/issues/12755
=> [release-2.2] Remove SelfLink 

pkg/controller/configurationpolicy/configurationpolicy_controller.go
for https://github.com/open-cluster-management/backlog/issues/13689
=> show name in status of partially noncompliant policy

README.md
=> build refresh for pkg vulnerability

pkg/controller/configurationpolicy/configurationpolicy_controller.go, pkg/controller/configurationpolicy/configurationpolicy_controller_test.go
This backport is to address issue https://github.com/open-cluster-management/backlog/issues/13182
Note that this is a backport to the 2.2 release.  Goal is to get this into 2.2.6
=> manual backport for issue 13182

pkg/controller/configurationpolicy/configurationpolicy_controller.go
Followup to PR:
- #136
Addresses issues:
- https://github.com/open-cluster-management/backlog/issues/13182
- https://github.com/open-cluster-management/backlog/issues/13940
=> Show details in status message

pkg/controller/configurationpolicy/configurationpolicy_controller.go, pkg/controller/configurationpolicy/configurationpolicy_utils.go, test/e2e/case12_list_compare_test.go, test/resources/case12_list_compare/case12_role_create_small.yaml, test/resources/case12_list_compare/case12_role_patch.yaml, test/resources/case12_list_compare/case12_role_patch_inform.yaml
open-cluster-management/backlog#13529
- fixes a bug where failures in the list compare function would cause a list item to be appended indefinitely to an object
- fixes a sort issue that was causing list compares to fail when they shouldn't have
=> fix sort compare bug and extra list items bug

cmd/manager/main.go
=> fix config-ppolicy-ctrl addon name

Makefile, pkg/controller/configurationpolicy/configurationpolicy_controller.go, pkg/controller/configurationpolicy/configurationpolicy_controller_test.go, pkg/controller/configurationpolicy/configurationpolicy_utils.go, test/crds/oauths.config.openshift.io_crd.yaml, test/e2e/case12_list_compare_test.go, test/resources/case12_list_compare/case12_oauth_create.yaml, test/resources/case12_list_compare/case12_oauth_patch.yaml, test/resources/case12_list_compare/case12_oauth_verify.yaml
https://github.com/open-cluster-management/backlog/issues/14331
=> sort template in merge fn

pkg/controller/configurationpolicy/configurationpolicy_controller.go
The logic here should be equivalent, and might be a bit more performant and easier to understand.
=> Refactor mergeArray

pkg/controller/configurationpolicy/configurationpolicy_controller.go, test/e2e/case12_list_compare_test.go, test/resources/case12_list_compare/case12_oauth_less_create.yaml, test/resources/case12_list_compare/case12_oauth_less_inform.yaml, test/resources/case12_list_compare/case12_oauth_less_patch.yaml, test/resources/case12_list_compare/case12_oauth_single_create.yaml, test/resources/case12_list_compare/case12_oauth_single_inform.yaml, test/resources/case12_list_compare/case12_oauth_single_patch.yaml
https://github.com/open-cluster-management/backlog/issues/14567
=> fix merge inconsistencies for 1 item lists

README.md
to trigger rebuild for https://github.com/open-cluster-management/backlog/issues/15227
=> update date in readme for rebuild

Makefile
https://github.com/open-cluster-management/backlog/issues/15525
=> update kubebuilder curl command

pkg/controller/configurationpolicy/configurationpolicy_controller.go
https://github.com/open-cluster-management/backlog/issues/14331
=> backport list fixes to 2.2

pkg/controller/configurationpolicy/configurationpolicy_controller.go, pkg/controller/configurationpolicy/configurationpolicy_controller_test.go, pkg/controller/configurationpolicy/configurationpolicy_utils.go
https://github.com/open-cluster-management/backlog/issues/15696
=> backport list merge fix to 2.3

pkg/controller/configurationpolicy/configurationpolicy_controller.go, pkg/controller/configurationpolicy/configurationpolicy_utils.go, test/e2e/case14_selection_test.go, test/e2e/e2e_suite_test.go, test/resources/case14_namespaces/case14_limitrange.yaml, test/resources/case14_namespaces/case14_limitrange_named.yaml, test/resources/case14_namespaces/case14_limitrange_unnamed.yaml
Fix for namespace selection when the resource is not named in the policy.
Issue https://github.com/open-cluster-management/backlog/issues/15614
=> handle namespace selection properly when the resource is unnamed

pkg/controller/configurationpolicy/configurationpolicy_controller.go
=> handle errors in hub templates

pkg/controller/configurationpolicy/configurationpolicy_controller.go
=> store api resource list in case of failure

pkg/controller/configurationpolicy/configurationpolicy_utils.go, test/e2e/case12_list_compare_test.go, test/resources/case12_list_compare/case12_byte_create.yaml, test/resources/case12_list_compare/case12_byte_inform.yaml
manual backport of open-cluster-management/backlog#17508
=> backport byte qty fix to 2.3 (#17508)

main.go
When the controller is running on older versions of Kubernetes such as
OCP 3.11, the lease API is not available. To support this, a new CLI
flag of --legacy-leader-elect was added. When enabled, the manager
will perform leader election using a ConfigMap rather than a lease. This
behavior is disabled by default.
Relates to:
open-cluster-management/backlog#17663
=> Allow using the legacy leader election method

pkg/controller/configurationpolicy/configurationpolicy_utils.go, test/e2e/case12_list_compare_test.go, test/resources/case12_list_compare/case12_byte_create.yaml, test/resources/case12_list_compare/case12_byte_inform.yaml
manual backport of https://github.com/open-cluster-management/backlog/issues/17508
=> [release-2.4] backport byte qty fix to 2.4 (#17508)

README.md, controllers/configurationpolicy_controller.go, go.mod, go.sum, main.go, pkg/common/common.go, pkg/common/kubeClient.go, pkg/common/operator-sdk-port.go, pkg/common/pattern_util.go, pkg/common/policyReader.go
For https://github.com/open-cluster-management/backlog/issues/18023, plus some refactoring that became more obvious while looking at the logs.
=> Unify logging

controllers/configurationpolicy_controller.go
This PR has the following changes:
* Check if policy templates are disabled once per configuration policy 
* Update objects once for all key mismatches 
See each commit for more details.
=> Small performance enhancements

pkg/controller/configurationpolicy/configurationpolicy_utils.go
fixes https://github.com/stolostron/backlog/issues/19160
and https://github.com/stolostron/backlog/issues/19257
=> backport byte quantity fix to 2.4

Makefile, controllers/configurationpolicy_controller.go, controllers/encryption.go, controllers/encryption_test.go, go.mod, go.sum, main.go, test/e2e/case16_policy_template_decryption_test.go, test/resources/case16_policy_template_decryption/policy-diff-key.yaml, test/resources/case16_policy_template_decryption/policy-invalid-iv.yaml, test/resources/case16_policy_template_decryption/policy-invalid-key.yaml, test/resources/case16_policy_template_decryption/policy.yaml, test/resources/case16_policy_template_decryption/secret-diff-key.yaml, test/resources/case16_policy_template_decryption/secret-invalid.yaml, test/resources/case16_policy_template_decryption/secret.yaml
Resolves:
https://github.com/stolostron/backlog/issues/18719
=> Add support for decrypting Hub encrypted strings in a policy

api/v1/configurationpolicy_types.go, deploy/crds/policy.open-cluster-management.io_configurationpolicies.yaml
https://github.com/stolostron/backlog/issues/19496
=> allow capital first letter in severity

controllers/configurationpolicy_utils.go
https://github.com/stolostron/backlog/issues/19501
https://github.com/stolostron/backlog/issues/19667
=> add namespaced check before appending ns string to status msg

pkg/controller/configurationpolicy/configurationpolicy_utils.go
https://github.com/stolostron/backlog/issues/19667
=> [release-2.4] add namespaced check before appending ns string to status msg

controllers/configurationpolicy_controller.go, main.go
Each commit describes the individual changes.
=> Small improvements

.github/workflows/kind.yml
The SonarCloud run failed, but it's mounting volumes in a Docker container so I suspect that I need to set the project directory for analysis. The debug logs will hopefully show this conclusively.
=> Add Sonar debugging

README.md
To accommodate for Prow build failures
=> no-op build

controllers/configurationpolicy_controller.go
This just reuses the object retrieved in the `objectExists` function
(renamed to `getObject`) later in the code.
=> Remove an unnecessary API call per object template

controllers/configurationpolicy_controller.go, test/e2e/case8_status_check_test.go, test/resources/case8_status_check/case8_pod_change.yaml, test/resources/case8_status_check/case8_pod_fail.yaml
Backport of issue to release 2.5
Refs:
- https://github.com/stolostron/backlog/issues/21908
=> Backport status and spec handling in enforced policy

.github/workflows/upstream-refs.yml, go.mod, go.sum
for https://github.com/stolostron/backlog/issues/21794
=> add upstream job from framework

README.md
Our periodic prow job monitoring detected the publish failure so just
creating this to push a change to run that job again.
=> Change to force a new publish job to run since last one failed

README.md
Prow publish and other jobs failed.  Need to re-run them.
=> Retry an update to config policy to re-run prow jobs

Makefile
Addresses:
- https://github.com/stolostron/backlog/issues/24402
=> Update E2E debug logs

.github/workflows/framework-kind.yml, .github/workflows/kind.yml, .github/workflows/upstream-refs.yml
Relates:
https://github.com/stolostron/backlog/issues/24763
=> Use the go.mod file for the Go version in CI

.github/workflows/kind.yml, .github/workflows/sonarcloud.yml
Relates:
https://github.com/stolostron/backlog/issues/25949
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
=> Allow SonarCloud coverage checks on PRs from forks

.github/workflows/sonarcloud.yml
=> `repository.owner.login` --> `repository_owner`

.github/workflows/sonarcloud.yml
See each commit for the changes.
=> Fix the sonarcloud workflow

.github/workflows/sonarcloud.yml
Relates:
https://github.com/stolostron/backlog/issues/25949
=> Pass in the SONAR_TOKEN secret to the SonarCloud reusable workflow

.ci-operator.yaml, api/v1/groupversion_info.go, build/Dockerfile, build/common/config/.golangci.yml, controllers/configurationpolicy_controller.go, go.mod, pkg/common/operator-sdk-port.go, test/utils/utils.go
- https://github.com/stolostron/backlog/issues/26060
Signed-off-by: Chunxi Luo <chuluo@redhat.com>
(cherry picked from commit 06071f76534d94ce60124ee81af53a7fb29e68af)
Closes #353
=> update go to latest version

controllers/configurationpolicy_controller.go, controllers/configurationpolicy_controller_test.go, test/e2e/case24_role_handling_test.go, test/resources/case24_role_handling/policy.yaml, test/resources/case24_role_handling/roles.yaml
This is a cherry-pick from #355.
Using this in favor of #358.
=> [release-2.5] Favor the existing array ordering and content when comparing arrays

.github/workflows/kind.yml, Makefile
Cherry-pick workflow updates from:
- #374
=> [release-2.5] Manual cherry-pick of #375

Makefile, controllers/configurationpolicy_controller.go, controllers/configurationpolicy_controller_test.go, controllers/metric.go, main.go, test/e2e/case21_alternative_kubeconfig_test.go, test/e2e/case25_related_object_metric_test.go, test/resources/case21_alternative_kubeconfig/parent-policy.yaml, test/resources/case21_alternative_kubeconfig/policy.yaml, test/resources/case25_related_object_metric/case25-test-policy.yaml, test/utils/utils.go
Syncs:
- https://github.com/open-cluster-management-io/config-policy-controller/pull/77
- https://github.com/open-cluster-management-io/config-policy-controller/pull/83
Closes #380
=> Manual upstream sync of #77 and #83

.ci-operator.yaml, api/v1/groupversion_info.go, build/Dockerfile, build/common/config/.golangci.yml, controllers/configurationpolicy_controller.go, go.mod, pkg/common/operator-sdk-port.go, test/utils/utils.go
ref: https://github.com/stolostron/backlog/issues/27048
=> [release-2.5] Upgrade to Go 1.19

README.md
This is due to the Prow job failing with a 401 error on the latest commit in the release-2.7 branch.
=> Trigger a Prow build

Makefile, go.mod, go.sum, test/e2e/case30_multiline_templatization_test.go
Manual sync of:
- https://github.com/open-cluster-management-io/config-policy-controller/pull/126
Closes #479
=> Upgrade go-template-utils to v3.2.0

Makefile, README.md
Our Hosted mode frame test always failed. This pr will fix the issue.
Thanks
Ref: https://issues.redhat.com/browse/ACM-5211
=> Hosted mode fix

.tekton/config-policy-controller-0pyc-pull-request.yaml, .tekton/config-policy-controller-0pyc-push.yaml, Dockerfile.rhtap
See the details in the associated task.
Refs:
- https://issues.redhat.com/browse/ACM-7178
=> Add rhtap dockerfile with allowed image references

controllers/configurationpolicy_controller.go, test/e2e/case34_enforce_w_status_test.go, test/resources/case10_kind_field/case10_kind_check.yaml
I had to make an adjustment to case34.
=> [Manual cherry-pick release-2.9] 🤖 Sync from open-cluster-management-io/config-policy-controller: #177, #178

controllers/configurationpolicy_controller_test.go, controllers/configurationpolicy_utils.go
A cherry-pick of #608, with conflicts resolved.
=> [release-2.7] CHERRYPICK: Fix items in nested lists not always being matched

controllers/configurationpolicy_controller.go, controllers/configurationpolicy_utils.go, test/e2e/case14_selection_test.go, test/e2e/case37_no_name_test.go, test/resources/case37_no_name/case37_bad_ingressclass.yaml, test/resources/case37_no_name/case37_bad_ingresses.yaml, test/resources/case37_no_name/case37_good_ingress.yaml, test/resources/case37_no_name/case37_no_name_clusterscope_policy.yaml, test/resources/case37_no_name/case37_no_name_clusterscope_policy_nothave.yaml, test/resources/case37_no_name/case37_no_name_policy.yaml, test/resources/case37_no_name/case37_no_name_policy_nothave.yaml
Ref: https://issues.redhat.com/browse/ACM-8782
Closes #684
=> Manual Cherry-pick Add relatedObjs to unamed mustnothave musthave

controllers/configurationpolicy_controller.go
Manual cherry-pick of:
- #769 
ref: https://issues.redhat.com/browse/ACM-10612
(cherry picked from commit b5b610b08a4a0b2c0fea0e5763962345f7b9aa60)
=> [release-2.10] Log "Forbidden" update errors

.tekton/config-policy-controller-acm-210-pull-request.yaml, .tekton/config-policy-controller-acm-210-push.yaml, build/Dockerfile, build/Dockerfile.rhtap
Also updates ubi8 --> ubi9
Contains changes from:
- #851 
ref: https://issues.redhat.com/browse/ACM-10739
=> [release-2.10] Use entitled Dockerfile for Konflux

main.go, test/e2e/case38_install_operator_test.go
Syncing the following PRs:
* open-cluster-management-io/config-policy-controller#259
* open-cluster-management-io/config-policy-controller#263
=> [2.10] Manual sync for OperatorPolicy namespace scoped watch

controllers/configurationpolicy_controller.go, controllers/configurationpolicy_controller_test.go
When policy is mustonlyhave for a ServiceAccount, infinite secrets are created due to consistent mismatch of imagePullSecrets and secrets fields. Thus, an exception is made to ignore those fields for ServiceAccounts.
Ref: https://issues.redhat.com/browse/ACM-12270
Signed-off-by: Jeffrey Luo <jeluo@redhat.com>
(cherry picked from commit 268514f5f53c066f47c7ed586fe77c388a82f6f3)
=> [2.9] Manual Sync for Ignore imagePullSecrets and secrets on ServiceAccounts #272

controllers/configurationpolicy_controller.go
Relates:
https://issues.redhat.com/browse/ACM-12958
=> [2.11] Add the censored diff message on OpenShift 3.11

test/crds/securitycontextconstraints.security.openshift.io_crd.yaml, test/e2e/case7_no_spec_test.go
Manual cherry-pick of:
- #997 
(cherry picked from commit a14266b6f6fca68b598fec6d06641a451a48503a)
=> [release-2.11] Use `--server-side` for `null` test

.github/workflows/kind.yml, controllers/configurationpolicy_controller.go, test/e2e/case1_pod_handling_test.go, test/resources/case1_pod_handling/ns_deleting.yaml, test/resources/case1_pod_handling/ns_nonexist.yaml
Syncing the following PRs:
* open-cluster-management-io/config-policy-controller#290
* open-cluster-management-io/config-policy-controller#291
* open-cluster-management-io/config-policy-controller#292
Closes #1008
=> 💁 Sync from open-cluster-management-io/config-policy-controller: #290

.ci-operator.yaml, .github/workflows/kind.yml, build/Dockerfile, build/Dockerfile.rhtap, controllers/configurationpolicy_controller.go, go.mod
ref: https://issues.redhat.com/browse/ACM-14251
=> [release-2.10] Update to Go v1.22

.ci-operator.yaml, build/Dockerfile, build/Dockerfile.rhtap, controllers/configurationpolicy_controller.go, go.mod
ref: https://issues.redhat.com/browse/ACM-14251
=> [release-2.11] Update to Go v1.22

go.mod, go.sum, main.go
Refs:
- https://issues.redhat.com/browse/ACM-12933
- https://issues.redhat.com/browse/ACM-17956
Co-authored-by: Jason Zhang <jaszhang@redhat.com>
(cherry picked from commit 426c9d0c30b8de7d257403182313c799fe79bad4) (cherry picked from commit 18e3dd2c86dca2fa53cc90c518f942f7e8fc235f)
=> [2.10] Ensure pod restart when target kubeconfig changes

go.mod, go.sum, pkg/dryrun/dryrun.go, pkg/dryrun/testdata/test_embed_policy/input_directory/input.yaml, pkg/dryrun/testdata/test_embed_policy/output.txt, pkg/dryrun/testdata/test_embed_policy/policy.yaml, pkg/dryrun/testdata/test_unwatchable_mappings/input_resource.yaml, pkg/dryrun/testdata/test_unwatchable_mappings/mappings.yaml, pkg/dryrun/testdata/test_unwatchable_mappings/output.txt, pkg/dryrun/testdata/test_unwatchable_mappings/policy.yaml, pkg/mappings/default-mappings.yaml, pkg/mappings/mappings.go
Syncing the following PRs:
- https://github.com/stolostron/config-policy-controller/pull/1245
- https://github.com/stolostron/config-policy-controller/pull/1272
Resolves the following issues:
- https://issues.redhat.com/browse/ACM-18135
- https://issues.redhat.com/browse/ACM-18827
=> [release-2.13] Sync main PRs 1245 and 1272

controllers/configurationpolicy_controller.go, test/e2e/case13_templatization_test.go, test/resources/case13_templatization/case13_objectname_var_invalid_skipobject.yaml, test/resources/case13_templatization/case13_objectname_var_outside_name_arg.yaml, test/resources/case13_templatization/case13_skipobject_multi_arg.yaml, test/resources/case13_templatization/case13_skipobject_non_bool.yaml
ref: https://issues.redhat.com/browse/ACM-19753
=> [release-2.13] Enable `skipObject` arguments

.tekton/config-policy-controller-acm-214-push.yaml
Refs:
- https://issues.redhat.com/browse/ACM-20948
=> Add multiarch build to konflux pipeline

controllers/configurationpolicy_controller.go, go.mod, go.sum, test/dryrun/context_vars/context_vars_test.go, test/dryrun/context_vars/object_pod/input.yaml, test/dryrun/context_vars/object_pod/output.txt, test/dryrun/context_vars/object_pod/policy.yaml, test/dryrun/context_vars/object_pod_default_func/input.yaml, test/dryrun/context_vars/object_pod_default_func/output.txt, test/dryrun/context_vars/object_pod_default_func/policy.yaml, test/dryrun/context_vars/object_pod_nsselector/error.txt, test/dryrun/context_vars/object_pod_nsselector/input.yaml, test/dryrun/context_vars/object_pod_nsselector/policy.yaml, test/dryrun/context_vars/object_templated_ns/error.txt, test/dryrun/context_vars/objectns_cluster_scoped/error.txt
ref: https://issues.redhat.com/browse/ACM-20863
(cherry picked from commit 1b132bc445f56de5aa00e7e432d2b62d52e55bc9)
Manual sync of:
- https://github.com/open-cluster-management-io/config-policy-controller/pull/368
Closes #1366
=> [manual-sync] fix: address`.Object` bugs

controllers/configurationpolicy_controller.go, controllers/configurationpolicy_controller_test.go, controllers/configurationpolicy_utils.go, controllers/configurationpolicy_utils_test.go, controllers/operatorpolicy_controller.go, test/e2e/case12_list_compare_test.go, test/e2e/case45_set_empty_field_test.go, test/resources/case12_list_compare/case12_byte_inform.yaml, test/resources/case12_list_compare/case12_oauth_less_inform.yaml, test/resources/case12_list_compare/case12_oauth_single_inform.yaml, test/resources/case12_list_compare/case12_oauth_verify.yaml, test/resources/case12_list_compare/case12_pod_inform.yaml, test/resources/case12_list_compare/case12_role_inform.yaml, test/resources/case12_list_compare/case12_role_patch_inform.yaml, test/resources/case22_pod_update_image/policy.yaml, test/resources/case45_set_empty_field/policy.yaml, test/resources/case45_set_empty_field/sriov_config.yaml, test/resources/case45_set_empty_field/sriov_config_crd.yaml
Cherry picks of https://github.com/stolostron/config-policy-controller/pull/1380 for release-2.13 and https://issues.redhat.com/browse/ACM-21801
=> [2.13] 21801 backport ocmio 366
